// Courses
export const RECEIVED_ALL_COURSES = "RECEIVED_ALL_COURSES";
export const RECEIVED_SINGLE_COURSE = "RECEIVED_SINGLE_COURSE";
export const CREATED_SINGLE_COURSE = "CREATED_SINGLE_COURSE";
export const UPDATED_SINGLE_COURSE = "UPDATED_SINGLE_COURSE";
export const DELETED_SINGLE_COURSE = "DELETED_SINGLE_COURSE";
export const UPDATED_COURSE_TITLE = "UPDATED_COURSE_TITLE";
export const UPDATED_COURSE_TAGLINE = "UPDATED_COURSE_TAGLINE";
export const UPDATED_COURSE_DESCRIPTION = "UPDATED_COURSE_DESCRIPTION";

export const UPDATE_SELECTED_COURSE = "UPDATE_SELECTED_COURSE";
export const UPDATE_COURSE_TITLE = "UPDATE_COURSE_TITLE";
export const UPDATE_COURSE_TAGLINE = "UPDATE_COURSE_TAGLINE";
export const UPDATE_COURSE_DESCRIPTION = "UPDATE_COURSE_DESCRIPTION";
export const CLEAR_SELECTED_COURSE = "CLEAR_SELECTED_COURSE";

// Chapters

// ExpressionSets
export const ADD_EXPRESSION_SET = "ADD_EXPRESSION_SET";
export const UPDATE_EXPRESSION_SET = "UPDATE_EXPRESSION_SET";

// Expressions
export const ADD_EXPRESSION = "ADD_EXPRESSION";
export const UPDATE_EXPRESSION = "UPDATE_EXPRESSION";
export const UPDATE_SELECTED_EXPRESSION = "UPDATE_SELECTED_EXPRESSION";
export const CLEAR_SELECTED_EXPRESSION = "CLEAR_SELECTED_EXPRESSION";

// ExerciseSets

// Exercises

// Screens - Course Selector
export const UPDATE_SEARCH_STRING = "UPDATE_SEARCH_STRING";
export const CLEAR_SEARCH_STRING = "CLEAR_SEARCH_STRING";

// Screens - Course Designer
export const TOGGLE_TABLE_OF_CONTENTS = "TOGGLE_TABLE_OF_CONTENTS";
export const FLIP_BOOK = "FLIP_BOOK";
export const RESET_BOOK_STATE = "RESET_BOOK_STATE";

// Screens - ExpressionSet Designer

// Navigation

// Notifications
export const FETCH_COMPLETE = "FETCH_COMPLETE";
export const FETCH_START = "FETCH_START";
export const FETCH_ERROR = "FETCH_ERROR";
